version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./Gateway
    ports: 
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./Characters
    ports: 
      - "8001:8001" 

  films:
    container_name: films
    restart: always
    build: ./Films
    ports: 
      - "8002:8002" 

  planets:
    container_name: planets
    restart: always
    build: ./Planets
    ports: 
      - "8003:8003" 
      
  database:
    container_name: database
    restart: always
    build: ./database
    ports: 
      - "8004:8004" 